// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFVAiaRKgAlc7dc37bA_oMALLuhH1skHo',
    appId: '1:583056892337:web:63b573a0be9b5a44ff5d90',
    messagingSenderId: '583056892337',
    projectId: 'registerlogin-6bf62',
    authDomain: 'registerlogin-6bf62.firebaseapp.com',
    storageBucket: 'registerlogin-6bf62.appspot.com',
    measurementId: 'G-366PMCZ9Y7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4W9r7gVVCNwc_jCF_Ygdbmdx3m8vS9Hw',
    appId: '1:583056892337:android:d3539fbe8650d89fff5d90',
    messagingSenderId: '583056892337',
    projectId: 'registerlogin-6bf62',
    storageBucket: 'registerlogin-6bf62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8leBsyt4BLBqekJBG7I55790geU5b-eA',
    appId: '1:583056892337:ios:dea4d4aabdab1031ff5d90',
    messagingSenderId: '583056892337',
    projectId: 'registerlogin-6bf62',
    storageBucket: 'registerlogin-6bf62.appspot.com',
    iosBundleId: 'com.example.signupSignin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8leBsyt4BLBqekJBG7I55790geU5b-eA',
    appId: '1:583056892337:ios:c20a608528b8dbffff5d90',
    messagingSenderId: '583056892337',
    projectId: 'registerlogin-6bf62',
    storageBucket: 'registerlogin-6bf62.appspot.com',
    iosBundleId: 'com.example.signupSignin.RunnerTests',
  );
}
